- tests/_test_process_executor.py
The joblib integration requires that job submission should be thread-safe (from a shared executor instance). This seems to be the case in the current queue based design. I added some tests to check some possible concurrent thread-based submission scenarii.
In particular I added a test to submit new tasks from a callback managed by the executor instance itself.
The fact that our executor is thread safe make it possible to remove the thread-local protection of the `get_reusable_executor` method. This will be tackled in another PR.
> Add tests for concurrent submissions

- .coveragerc
- continuous_integration/install.sh
- continuous_integration/install_coverage_subprocess_pth.py
- continuous_integration/test_script.sh
- tox.ini
This PR configures both tox and travis to use the `COVERAGE_PROCESS_START` environment variable in conjunction with a `.pth` file that enables coverage traces with `import coverage; coverage.process_startup()` so as to collect coverage data both in the main process and all its children process.
http://coverage.readthedocs.io/en/latest/subprocess.html
This setting could be further simplified by using tox in travis via the `TOXENV` variable but thus will be done in a later PR.
> Setup test coverage with subprocess support

- tests/_test_process_executor.py
- tests/test_futures.py
- tests/test_process_executor_fork.py
- tests/test_process_executor_forkserver.py
- tests/test_process_executor_loky.py
- tests/test_process_executor_spawn.py
- tests/test_reusable_executor.py
- tox.ini
Instead of a custom fixture based on faulthandler that does not interact well with py.test log capture.
> [MRG] use pytest-timeout globally

- .travis.yml
- continuous_integration/build_test_ext.sh
- continuous_integration/travis/runtests.sh
- loky/process_executor.py
- setup.py
- tests/_openmp/_fail_fork.py
- tests/_openmp/parallel_sum.pyx
- tests/_openmp/setup.py
- tests/_test_process_executor.py
- tests/test_loky_backend.py
- tests/test_process_executor_fork.py
- tox.ini
Run a simple openMP cython program to ensure the compatibility of our new backend with this library, as proposed in #18 .  
For the moment, appveyor does not seem to allow compillation with openMP, so the test is not good in windows.
> Test Openmp compatibility

- .travis.yml
- loky/_base.py
- loky/backend/__init__.py
- loky/process_executor.py
- tests/_executor_mixin.py
- tests/_openmp/setup.py
- tests/_test_process_executor.py
- tests/script_helper.py
- tests/test_futures.py
- tests/test_loky_backend.py
- tests/test_reusable_executor.py
- tests/utils.py
Tackles #21 and accelerate the slowest tests.
Use `Event` objects to synchronize the processes in tests.
Improve handeling of Broken vs Shutdown.
> Concurrent.futures compatible Errors

- loky/process_executor.py
- tests/_executor_mixin.py
- tests/_test_process_executor.py
Either on GC or on main Python program exit.
TODO:
> More tests to check clean shutdown behavior

- .travis.yml
- continuous_integration/travis/runtests.sh
- loky/backend/process.py
- loky/backend/semlock.py
- loky/backend/synchronize.py
- tests/_test_process_executor.py
- tests/test_loky_backend.py
- tests/test_semlock.py
- tox.ini
There is an issue with our pthread semlock implementation. As we convert the result of `sem_open` to a `ctypes.c_void_p`, SEM_FAILURE does not have the right value and we do not detect failure properly.  
This behavior lead to silent failures such as #42 and should be fixed by properly checking for failure on `sem_open` and handling correctly the error number.
> Fix semlocks

- loky/reusable_executor.py
- tests/_executor_mixin.py
- tests/_test_process_executor.py
- tests/test_reusable_executor.py
It might be useful to make it possible to not wait for previous job completion to get a new reusable executor.
> [MRG] Make it possible to pass kill_workers=True to get_reusable_executor

- .coveragerc
- .travis.yml
- continuous_integration/appveyor/runtests.ps1
- loky/__init__.py
- loky/_base.py
- loky/backend/__init__.py
- loky/backend/_posix_reduction.py
- loky/backend/_posix_wait.py
- loky/backend/_win_reduction.py
- loky/backend/_win_wait.py
- loky/backend/connection.py
- loky/backend/context.py
- loky/backend/fork_exec.py
- loky/backend/managers.py
- loky/backend/popen_loky.py
- loky/backend/process.py
- loky/backend/queues.py
- loky/backend/reduction.py
- loky/backend/semaphore_tracker.py
- loky/backend/semlock.py
- loky/backend/spawn.py
- loky/backend/synchronize.py
- loky/process_executor.py
- loky/reusable_executor.py
- tests/_executor_mixin.py
- tests/_openmp/setup.py
- tests/test_loky_backend.py
- tests/test_reusable_executor.py
- tox.ini
Now that we have a backport of the context object, we should reduce our code overhead and clean the backported files from any unnecessary code.
> Refactor backported code

- loky/process_executor.py
Otherwise the unsafe "fork" context is used by default.
> Use the "loky" context by default

- tests/_test_process_executor.py
Some Python version (e.g. 3.5.2) print debug info on stdout which makes
stdout parsing unreliable to monitor the successful worker completion.
> Make test_interpreter_shutdown more robust

- loky/process_executor.py
- tests/test_loky_backend.py
There was an extra `flag_current_thread_clean_exit` which broke the test randomly
> FIX shutdown with sys exit at pickle

- loky/backend/popen_loky_posix.py
- loky/backend/semaphore_tracker.py
This will make it easier and safer to do source code imports rewrite to
vendor loky in third-party libraries such as joblib and scikit-learn.
To be included in 1.1.3.
> [MRG] Avoid module names as string

- loky/backend/_win_reduction.py
- loky/backend/_win_wait.py
- loky/backend/compat_win32.py
- loky/backend/popen_loky_posix.py
- loky/backend/popen_loky_win32.py
- loky/backend/semlock.py
When vendoring loky into joblib and then into scikit-learn some tools such as test runners or test_common of scikit-learn try to recursively import all the modules. Modules that import windows-only system tools subsequently fail.
While we could fix the introspection tools everywhere, I have the feeling it would be less intrusive to have loky modules protect their OS specific modules.
This PRs does so for windows specific imports under POSIX.
> [MRG] ENH protect windows imports under POSIX

- appveyor.yml
- continuous_integration/appveyor/runtests.ps1
- loky/backend/compat_win32.py
- loky/process_executor.py
- tests/test_loky_backend.py
- tox.ini
and fix copy-pasted comment in appveyor.yml.
Since we use tox the Python version is not important, just the platform is. However we don't want to give the impression that legacy Python 2.7 is a reasonable default nowadays :)
The issue was revealed by the scikit-learn CI tests: https://github.com/scikit-learn/scikit-learn/pull/9486
> [WIP] actually test for 64 bit Python on appveyor

- loky/process_executor.py
- tests/_test_process_executor.py
- tests/test_reusable_executor.py
So as to reuse an existing exception from Python 3.3+
concurrent.futures module.
> [MRG] rename BrokenExecutor as BrokenProcessPool

- CHANGES.md
- loky/process_executor.py
- tests/test_reusable_executor.py
This is to ensure that code written for `concurrent.futures` will still work when using the `ProcessPoolExecutor` implementation from loky.
> [MRG] ensure exception compatibility with concurrent.futures

- loky/backend/queues.py
- loky/process_executor.py
Fix for the following exceptions fond in joblib test logs under Python 3.6:
```
Exception in thread QueueManagerThread:
Traceback (most recent call last):
File "/volatile/ogrisel/code/joblib/joblib/externals/loky/process_executor.py", line 491, in shutdown_all_workers
call_queue.put_nowait(None)
File "/usr/lib/python3.6/multiprocessing/queues.py", line 129, in put_nowait
return self.put(obj, False)
File "/usr/lib/python3.6/multiprocessing/queues.py", line 83, in put
raise Full
queue.Full
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/usr/lib/python3.6/threading.py", line 864, in run
self._target(*self._args, **self._kwargs)
File …
```
> FIX full queue exception at shutdown

- .travis.yml
- CHANGES.md
- continuous_integration/appveyor/runtests.ps1
- continuous_integration/travis/runtests.sh
- loky/process_executor.py
- loky/reusable_executor.py
- tests/test_reusable_executor.py
- tox.ini
Added a new test with several threads concurrently using the same reusable executor. Found an issue, added a fix.
Let see if this test can find new bugs on the CI.
> [MRG] add a new test: test_reusable_executor_thread_safety

- loky/backend/spawn.py
Fix for #124 
We do not correctly support the `freeze_support` for win32 and python2.7.
This behavior should be tested.
> FIX freeze_support for win32+py27

- CHANGES.md
- loky/backend/utils.py
- loky/process_executor.py
- tests/test_loky_backend.py
This should avoid leaving unattended processes, which freeze the shutting down process of the python interpreter.
> ENH safe terminate for nested processes

- CHANGES.md
- docs/API.rst
- docs/_static/custom.css
- docs/conf.py
- examples/reuseable_executor.py
- loky/backend/context.py
- loky/backend/utils.py
- loky/cloudpickle_wrapper.py
- loky/process_executor.py
- tests/_test_process_executor.py
Consistently serialize function from `__main__` with `cloudpickle` when it is available.
Fix #146
>  ENH use cloudpickle wrapper for initializer 

- loky/backend/compat.py
Closes https://github.com/tomMoral/loky/issues/157
`import _pickle` accesses a private CPython module and consequently this fails on PyPy.
> Fix private  _pickle import

- .travis.yml
- continuous_integration/travis/runtests.sh
- loky/backend/reduction.py
- loky/process_executor.py
- tests/_test_process_executor.py
- tests/test_process_executor_forkserver.py
- tests/test_process_executor_spawn.py
- tox.ini
This should fix #160 reported by @rth for scikit-learn 0.20.
I decided to skip tests for the Spawn-based and ForkServer-based process pool executors under PyPy as they are not stable apparently. They are not used in joblib / scikit-learn though.
Let's see if the CI likes it.
> Add support for PyPy

- CHANGES.md
- docs/API.rst
- docs/conf.py
- examples/cloudpickle_wrapper.py
- loky/__init__.py
- loky/backend/__init__.py
- loky/backend/queues.py
- loky/backend/reduction.py
- loky/cloudpickle_wrapper.py
- loky/process_executor.py
- tests/_test_process_executor.py
- tests/test_cloudpickle_wrapper.py
- tests/test_reusable_executor.py
- tests/test_worker_timeout.py
- tests/utils.py
- tox.ini
Add a wrapper for non-picklable objects to use `cloudpickle` for their serialization.
This PR also add a test for `cloudpickle_wrapper.py` to ensure its behavior is working as expected.
> ENH wrapper for non picklable objects

- loky/backend/semaphore_tracker.py
Set `BrokenPipeError` to `IOError` for python2.
fix #185
> FIX BrokenPipeError compatibility for python2.7

- loky/backend/utils.py
- loky/process_executor.py
Looping on values of a dict is not thread-safe. However, it is thread safe to loop on `list(d.values())`, as shown by the following snippet
```python
import time
a = dict([(i, i) for i in range(1000000)])
def rm_elem(a):
for i in range(1000):
time.sleep(.001)
del a[i]
print("done")
import threading
t = threading.Thread(target=rm_elem, args=(a,))
t.start()
for i in range(100):
time.sleep(.001)
[v for v in list(a.values())]
```
Replacing `[v for v in list(a.values())]` by `[v for v in a.values()]` makes the snippet fails on both `python` and `pypy`.
Close #190
> FIX thread safety of looping on processes

- tests/test_reusable_executor.py
- tests/utils.py
This test should fail with any release of cloudpickle after 0.5.4 up to the current stable release (0.7.0 at this time).
I tested locally that https://github.com/cloudpipe/cloudpickle/pull/240 makes it pass.
I believe this further highlights that the change introduced in cloudpickle 0.5.4 is actually a bug.
> Add test for nested interactively defined functions with code changes

- loky/backend/reduction.py
If a `Pickler` instance already has methods in its dispatch table, do not override them. This bug showed up in https://github.com/cloudpipe/cloudpickle/pull/253 and running [this benchmark](https://gist.github.com/pierreglaser/26207c20dd8526d6df7963044a3e4477) where the `Cloudpickler` instances derives from the C `_Pickler` and most custom saving methods are inside `dispatch_table`, not `dispatch`.
Given the current `set_loky_pickler` structure (private, nested `CustomizablePickler` class), it is hard to write a proper test for it.
> FIX do not override Pickler's dispatch_table

- loky/backend/context.py
- loky/backend/semaphore_tracker.py
- loky/backend/spawn.py
- tests/test_semaphore_tracker.py
Closes #200.
At the end, the passing of the `_pid` attribute was implemented, but there was a typo.
Adding a test alongside with it.
> FIX  _pid attribute passing of semaphore_tracker 

- .travis.yml
- tests/test_loky_backend.py
Follow up on #209 
The recent CI failures were caused by a leaked file descriptor in `PyPy`: [ioopen-directory-leaks-a-file-descriptor](https://bitbucket.org/pypy/pypy/issues/3021/ioopen-directory-leaks-a-file-descriptor).
Now that we identified the issue, I think we should simply skip the failing test, and not allow the test suite run to fail.
> CI skip file descriptor test for PyPy

- loky/backend/compat_win32.py
- loky/backend/popen_loky_posix.py
- loky/backend/popen_loky_win32.py
- loky/backend/reduction.py
- loky/backend/resource_tracker.py
- loky/backend/spawn.py
- loky/backend/synchronize.py
- tests/_executor_mixin.py
- tests/_test_process_executor.py
- tests/test_resource_tracker.py
- tests/test_semaphore_tracker.py
This PR aims at extending the current `SemaphoreTracker` to make it able to track more generic named resources, such as folders, and potentially `memmap` and shared memory.
Many small changes in files because of the name refactoring. The main change is the registering/unregistering API extension: when one wants to track a new resource, one must (along with the resource name), specify the resource type. This is necessary for the `RessourceTracker` to know which cleanup function to use for each resource before shutdown.
Base branch: https://github.com/tomMoral/loky/pull/202
> ENH add ResourceTracker to improve ressource clean up

- CHANGES.md
- loky/backend/resource_tracker.py
Fixes the failures that appeared in joblib/joblib#888 while vendoring the new `cloudpickle` and  `loky` inside `joblib`.
> FIX skip waitpid on Windows

- CHANGES.md
- appveyor.yml
- continuous_integration/appveyor/runtests.ps1
- loky/backend/popen_loky_win32.py
Fixes the error reported in joblib/joblib#901, namely that joblib does not work from inside a virtual environment on windows for Python3.7+. This is due to a change in the python's virtualenv executables.
> Fix loky for windows + python3.7 inside venv

- CHANGES.md
- continuous_integration/appveyor/runtests.ps1
- loky/backend/fork_exec.py
- loky/backend/popen_loky_posix.py
- loky/backend/popen_loky_win32.py
- loky/backend/process.py
- loky/backend/spawn.py
- loky/process_executor.py
- loky/reusable_executor.py
- tests/_test_process_executor.py
- tests/conftest.py
- tests/test_loky_backend.py
Pass environment variable to child process first to avoid mixed effect after module loads.
TODO:
> ENH pass env var to child

- .azure_pipeline.yml
- .coveragerc
- tox.ini
Report coverage on stdout for each individual CI job and skip coverage upload explicitly for joblib tests.
> Try to improve coverage reporting on CI

- .azure_pipeline.yml
- tests/_test_process_executor.py
We recently temporarily removed the `Python 3.8` entries of the CI due to a failing test caused by a reference cycle in early `Python 3.8` versions. Now that this bug is fixed upstream, we can skip the failing test on the appropriate Python versions where this bug exists, and restore the rest of the CI suite.
> restore Python 3.8 CI entries and fix a test

- CHANGES.md
- loky/backend/popen_loky_posix.py
- loky/backend/resource_tracker.py
- loky/backend/spawn.py
- tests/test_loky_backend.py
- tests/test_resource_tracker.py
Complements (supersedes?) #242 
`loky` processes should inherit `multiprocessing`'s `resource_tracker` so that `register/unregister` requests of `SharedMemory` objects can be successfully executed from them.
Note that in response to https://github.com/joblib/loky/pull/242#issuecomment-620027480: `loky` indeed has to call `ensure_running` before launching its' process.
@arquolo I'm sorry if you already started to work on this. I'd rather have this merged soon because it blocks a whole series of PR (and especially joblib/joblib#966).
cc @tomMoral @ogrisel
> make loky process inherit multiprocessing's resource_tracker

- CHANGES.md
- loky/backend/queues.py
- loky/process_executor.py
- loky/reusable_executor.py
- tests/_test_process_executor.py
> ENH backport cpython modification in loky

- README.rst
- setup.py
the `codecov` badge and the `setup.py` `url`, still reference `tomMoral/loky`. We may want to change it and release `2.7.1` as this makes the package look "fishy"/"phony" on PyPI (no stars, no issues, 1 fork)... see https://pypi.org/project/loky/
@tomMoral @ogrisel
> stop referencing tomMoral/loky

- CHANGES.md
- loky/reusable_executor.py
- tests/test_reusable_executor.py
the `get_reusable_executor` function call makes it difficult for third party libraries (like `joblib`) to subclass the (admittedly private) `_ReusablePoolExecutor` class. I propose to change this by making `get_reusable_executor` wrap a `classmethod` and thus stop hardcoding a `_ReusablePoolExecutor` constructor  inside it.
> Increase ReusablePoolExecutor extensiblity

- CHANGES.md
- loky/backend/reduction.py
- tests/test_cloudpickle_wrapper.py
This is a tentative fix for #259 based on something suggested by @pierreglaser in https://github.com/joblib/loky/pull/260#issuecomment-696685968.
However it does not work the way I thought it would. I am opening the PR anyway to share my understanding with @pierreglaser (and other people interested in this problem). The interesting part is that using the member descriptor to set the custom `dispatch_table` on the pickler is actually changing the class and not the instance.
> [MRG] Fix custom reducers registered in dispatch_table handled by a member descriptor 

- CHANGES.md
- loky/backend/context.py
- tests/test_loky_module.py
Fixes #223 
adds a parameter to cpu_count: `maybe_physical_only`. When True it will return the number of physical cores instead of the number of logical cpus unless the number of available cpus is modified in which case we respect it (hence the "maybe" in the param name).
It's not as complete as `psutil.cpu_count(logical=False)` but it does not require compiled code.
Since it makes subprocess calls, the result is cached for efficiency.
> Add option to count only physical cores in cpu_count

- README.md
Add some explanation on why `loky`.
Closes #274
> DOC add explanation on the name `loky` in README

- tests/test_reusable_executor.py
Reading the code to understand the [test failure](https://dev.azure.com/joblib/loky/_build/results?buildId=939&view=logs&j=1d8c3303-934c-55f6-9232-8cce53380890&t=775c9ee0-f2ae-500c-4b35-a4615d47f0da) from #276, I found out that the function name was confusing.
However I still do not understand the cause of the problem (why do we have a worker process terminated that early, right after the creation of the 13 workers process pool). The captured debug log does not seem too explicit to me.
Note that this failure is random.
> cosmetics: better test helper name

- tests/test_reusable_executor.py
Fix test_reusable_executor to load libc via "c" library rather than
"libc".  The latter is incorrect, and does not work in the newest
versions of Python anymore, see https://bugs.python.org/issue42580.
> FIX load libc correctly in test_reusable_executor

- .azure_pipeline.yml
- CHANGES.md
- continuous_integration/runtests.sh
- loky/initializers.py
- loky/process_executor.py
- tests/_test_process_executor.py
- tox.ini
Fix #297.
I decided to move the registry design discussion to a later issue.
To write such a registry we need take into account several design constraints into account:
- per-worker vs per-function-call contexts with setup/teardown (see: https://github.com/scikit-learn/scikit-learn/blob/3ae7c7615343bbd36acece57825d8b0d70fd9da4/sklearn/utils/fixes.py#L189-L196)
- thread-safety / side effect isolation of per-function-call contexts for threadpool executors / dask executors with multiple threads per workers
- shall we allow custom teardowns for per-worker inits?
VizTracer would only be one use case. sklearn, pandas and warnings config would be others.
> Initialize viztracer in worker processes

- loky/backend/synchronize.py
- tests/test_resource_tracker.py
- tests/test_synchronize.py
- tests/utils.py
The ctypes-based implementation of `SemLock` for Python 2.7 does not work on macOS 11 and I have no idea why (I get `EINVAL` randomly when creating new semlocks).
It works with the `_multiprocessing` implementation though, so in practice `loky` works fine with recent versions of Python on macOS 11. So instead of trying to fix the ctypes implementation, I changed the test to use `_multiprocessing`  when available.
We might want to get rid of Python 2.7 support and the ctypes implementation of semlock to lower the maintenance burden. This PR is a first tiny step in that direction.
> MAINT make tests pass on macOS 11

- CHANGES.md
- loky/process_executor.py
- tests/_test_process_executor.py
This test is failing on my machine. With the new code, the error message is more informative:
```python-traceback
E           AssertionError: Exception ignored in: <function _ExecutorManagerThread.__init__.<locals>.weakref_cb at 0x118f8a3a0>
E           Traceback (most recent call last):
E             File "/Users/ogrisel/code/loky/loky/process_executor.py", line 517, in weakref_cb
E           AttributeError: 'NoneType' object has no attribute 'util'
```
but the test can be improved without waiting for a fix for this bug it the CI is green.
> Fix random failure in test_interpreter_shutdown and improve a failure message in test_hang_issue39205

- tests/utils.py
The following tiny refactoring should give us more informative failure messages.
> Make time relative test failures more informative

- loky/process_executor.py
- loky/reusable_executor.py
- tests/_test_process_executor.py
- tests/test_process_executor_forkserver.py
- tests/test_process_executor_spawn.py
- tests/test_reusable_executor.py
Part of https://github.com/joblib/loky/pull/304. Remove py < 3.7 support in process_executor and reusable_executor
> MNT drop py < 3.7 support for process_executor and reusable_executor

- tests/test_loky_backend.py
This should kill one of the remaining unstable test on macos on the CI.
/cc @jeremiedbb @glemaitre
> Fix inconsistency in unstable test_terminate

- loky/backend/fork_exec.py
> MNT drop py < 3.7 support in fork_exec

- loky/backend/__init__.py
> MNT drop py < 3.7 support in backend init

- tests/test_worker_timeout.py
> MNT drop py < 3.7 support in test_worker_timeout

- continuous_integration/install_coverage_subprocess_pth.py
- loky/backend/context.py
- loky/backend/utils.py
- setup.py
- tests/_executor_mixin.py
- tests/_test_process_executor.py
- tests/test_cloudpickle_wrapper.py
- tests/test_loky_backend.py
- tests/test_loky_module.py
- tests/test_resource_tracker.py
- tests/utils.py
Towards #304 
Uses python string instead of bytes.
Uses text in subprocess methods.
> MAINT use plain text in subprocess

- tests/_test_process_executor.py
- tests/test_synchronize.py
Hopefully fixes #338.
It's likely that #348 has already fixed the flaky `test_processes_crash_handling_after_executor_gc`
observed in #338 because the executor is flagged as broken in this test and therefore the workers should now be SIGKILLed faster (at least on POSIX) but while reading the stderr trace of #338 to understand the race condition I suspect that this can also happen `test_processes_terminate_on_executor_gc` where the workers are terminated without a kill which can be slower than expected on an overloaded CI with coverage data dumped to disk.
Let's be rather safe than sorry.
https://twitter.com/Nick_Craver/status/1489421247381389312
> Fix flaky test processes crash handling after executor gc

- continuous_integration/runtests.sh
- tests/_test_process_executor.py
Bumps the timeout to 30s (instead of 10s) as PyPy processes can be significantly slower to start-up than CPython, despite the recently merged #349. If it still fails, maybe there is a real deadlock and that would not be just a false positive of a too strict test.
Also: raise the timeout exception if it occurs instead of formatting the traceback as the message of an AssertionError.
> Increase timeout in test_thread_safety for PyPy

- CHANGES.md
- loky/backend/context.py
- tests/test_loky_module.py
Fixes #354.
Now `test_cpu_count_cfs_limit` passes locally on my macOS machine with a recent host Linux kernel in the docker VM.
> Use /sys/fs/cgroup/cpu.max for CPU quotas

- CHANGES.md
- loky/backend/utils.py
Fix #356.
Follow-up #348.
Make the windows and the posix variants more symmetric.
For both platform families, if the system-specific tree kill method fails for
any reason other than process not found, log a warning message with the
traceback and recommand the user to install psutil, and try to terminate the
the root process to avoid the stalled shutdown observed in #356 on Windows.
> Improve _kill_process_tree_without_psutil

- CHANGES.md
- loky/backend/context.py
- tests/test_loky_module.py
Follow-up on  #354.
- cgroup v2 does not refer to the name of a particular Linux  scheduler anymore;
- extract the Cgroup related logic in a dedicated helper function to make the code easier to follow and potentially use that helper function in isolation when debugging;
- added comment to make it explicit what is related to cgroup v1  what is related to cgroup v2;
- linked to the kernel.org doc;
- updated the docstring accordingly.
> Rename CFS to Cgroup in cpu_count doc and local variables

- CHANGES.md
- loky/__init__.py
- loky/backend/context.py
- loky/backend/resource_tracker.py
- loky/backend/synchronize.py
- loky/process_executor.py
I took the opportunity of this PR to better document why we cannot remove the remaining multiprocessing backport files.
TL;DNR: we will probably be able to remove even more once we drop support for Python 3.7 since the resource tracker was contributed upstream in Python 3.8.
> Release 3.1.0

- loky/process_executor.py
- tests/test_reusable_executor.py
```python
#!/usr/bin/env python
import os
import subprocess
import loky
with loky.get_reusable_executor(timeout=10, kill_workers=True) as p:
list(p.map(lambda x: x, range(1000)))
subprocess.check_call(f'kill -9 {os.getpid()}', shell=True)
```
After the above process dies, there are `python -m loky.backend.popen_loky_posix --process-name LokyProcess-` processes left hanging for ever, causing memory leaks on the target server.
The real life scenario is getting SIGKILL (by OOM handler) and causing further memory leak.
> Fix a deadlock when a parent process is killed with SIGKILL

- continuous_integration/runtests.sh
- tests/test_loky_module.py
> MAINT Update python:3.7 to python:3.10 in tests that rely on docker

- CHANGES.md
- loky/process_executor.py
- tests/_executor_mixin.py
- tests/test_reusable_executor.py
Adapted reproducer for #369 to be part of the loky test suite.
Unfortunately I could never trigger the race condition locally so far.
> TST test_error_in_nested_call_keeps_resource_tracker_silent

- loky/reusable_executor.py
VAL/VAR issue in the doco, noticed its from this doc string.
Links and resovles issue #377
> DOC: Update 'VAR' to 'VAL' in reusable_executor.py

- loky/process_executor.py
Does not fix the performance problem on the PyPy CI but at least the logs are cleaner.
> ENH avoid spurious atexit outputs about thread wakeups for shutdown executors

- tests/test_reusable_executor.py
Apparently there was a race condition I would always trigger on my local machine in this test utility.
Weirdly enough it would not be triggered by the CI...
> FIX AttributeError in clean_warning_registry

- .azure_pipeline.yml
- loky/backend/synchronize.py
- tox.ini
Let's tests on more recent Python versions as well.
I removed CPython 3.7 from the matrix but we still test for Python 3.7 via PyPy. We would need to also bump it up but I think we can do that in a dedicated PyPy PR.
Note that testing with Python 3.11 might make the pytest orderning non-deterministic and might reveal old yet hidden bugs such as the one being investigated in #388.
> MAINT bump-up CI versions

- CHANGES.md
- loky/backend/context.py
- loky/process_executor.py
- tests/test_loky_module.py
- tests/test_reusable_executor.py
Fixes #192.
`loky.cpu_count` never returns more than 61 on Windows.
I the user explicitly ask for more than 61 workers on Windows, a warning is raised and `max_workers` is automatically set back to the 61 limit.
I added a new test that checks this by trying to spawn 62 workers. I ran the tests locally on windows and macos and it takes around 10-15s to run locally. I hope this will be ok on the CI, otherwise, I can disable it my default on (some) CI environments. Let's see.
> FIX make sure max_workers cannot exceed 61 on windows

- loky/process_executor.py
I noticed this when running the joblib tests
> MAINT Add missing f prefix for f-string

- loky/reusable_executor.py
Originaly reported in joblib/joblib#1464, but overrided by vendoring process.
> DOC fix repeated words

- .github/workflows/test.yml
- .gitignore
In https://github.com/joblib/loky/pull/430, the introduction of a first workflow doesn't run on the PR. It seems that it has to already be on master (or at least that at least 1 workflow already exist on master ? I don't know).
So I've been testing it on my fork and it seems to work, see https://github.com/jeremiedbb/loky/pull/1. But It's not complete. For instance it doesn't check the coverage.
So I propose to merge a very small subset (i.e. just the linting part) which has been tested on my fork and should be pretty safe first so that we have the workflow on master. Then I can keep working on https://github.com/joblib/loky/pull/430, to make sure that everything is fine, including the coverage for instance, directly on the main repo.
> CI First workflow

- tests/test_resource_tracker.py
- tests/test_reusable_executor.py
To make it easier to debug the cause of warnings that are randomly occurring on CI runs but not on local machines.
> More informative assertion errors on unexpected warnings

- CHANGES.md
- loky/process_executor.py
- tests/_executor_mixin.py
- tests/_test_process_executor.py
Trying to reproduce #437 in the current `master` branch.
EDIT: reproduced at d833e8f and fixed by c4217e4.
Fixes #437.
> FIX deadlock in test_shutdown_with_sys_exit_at_pickle

- CHANGES.md
- loky/process_executor.py
- tests/_test_process_executor.py
- tests/test_reusable_executor.py
Automatically call `faulthandler.enable()` by default to dump extra debug info to crashed workers' stderr, typically on SIGSEV, SIGBUS and co.
I also expanded the error message of `TerminatedWorkerError` to point the users to look at stderr for more details. This should help us debug stability problems on our CI but also assist our users and interact more productively with them when they report problems.
> ENH enable faulthandler traceback reporting on worker crash by SIGSEV

- .github/workflows/test.yml
I could not find any reference of `SKLEARN_TESTS` in the repo.
> MAINT typo in the codecov step of the GHA config

- .github/workflows/publish-to-pypi.yml
As documented here https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
- builds the wheel and source distribution
- upload to test pypi on every push to master (although actually skips the upload if the same version already exists)
- upload to pypi on tagging.
- drafts a github release if the upload to pypi is successful.
Requires setting-up trusted publisher on both pypi and test pypi before merging.
> Add github workflow to automatically publish to pypi

- CHANGES.md
- loky/backend/context.py
Implement physical core detection on FreeBSD using the kern.smp.cores sysctl, which returns the number of physical CPU cores on the system.
> Support retrieving physical core count on FreeBSD
