.coveragerc, .gitignore, appveyor.yml, continuous_integration/install.sh, continuous_integration/test_script.sh, tox.ini
=> Refactoring coverage collection to aggregate reports generated by tox

.coveragerc, continuous_integration/appveyor/runtests.ps1, continuous_integration/travis/runtests.sh, loky/process_executor.py, loky/reusable_executor.py, tests/_test_process_executor.py, tests/test_reusable_executor.py
This PR tackles some issues reported in #20.
The PR is set to WIP to get code coverage report on the go while doing the refactoring so as to use CI to identify dead code or untested branches.
=> [WIP] Code cleanup in reusable_executor.py and tests

continuous_integration/appveyor/runtests.ps1, loky/backend/__init__.py, loky/backend/popen_loky.py, loky/backend/semlock.py, loky/backend/synchronize.py, tests/_executor_mixin.py, tests/conftest.py, tests/script_helper.py, tests/test_loky_backend.py, tests/test_reusable_executor.py, tox.ini
Test pipe handeling for windows.
Improve readability in the test.
=> Improve synchronization object testing

loky/process_executor.py, tests/_executor_mixin.py, tests/_test_process_executor.py, tests/test_loky_backend.py, tox.ini
Found a bug by adding a new test.
Fix for #39.
=> [MRG] Fix crash after gc

loky/backend/__init__.py, loky/backend/context.py, loky/backend/managers.py, loky/backend/popen_loky.py, loky/backend/process.py, loky/backend/queues.py, loky/backend/reduction.py, loky/backend/semlock.py, loky/backend/spawn.py, loky/backend/synchronize.py, loky/process_executor.py, setup.py, tests/_executor_mixin.py, tests/_test_process_executor.py, tests/conftest.py, tests/test_loky_backend.py, tests/test_process_executor_loky.py, tox.ini
Add the possibility to customize the serialization of the objects in `PoolProcessExecutor`.
=> Customizable serialization

tests/test_reusable_executor.py
The new version of pytest reports uncaught warnings. This is a good opportunity to actually add checks for resize warnings.
=> TST check for executor resize warnings

examples/deadlock_on_shutdown.py, loky/backend/queues.py, loky/backend/utils.py, loky/process_executor.py, loky/reusable_executor.py, tests/_test_process_executor.py, tests/test_loky_backend.py, tests/test_reusable_executor.py
In particular deadlocks as reported in #75 and probably #71 as well.
=> [WIP] fixing shutdown issues

tests/_test_process_executor.py
This should be uncontroversial. I plan to merge as soon as CI is green.
=> [MRG] minor cleanup of test_interpreter_shutdown

loky/process_executor.py
=> [MRG] thread safe access to processes in QueueManager

loky/process_executor.py
This should help debug #90 the next time it happens on CI.
=> [MRG] add more debug logs to queue manager thread

loky/process_executor.py, tests/test_reusable_executor.py
This is a tentative non-regression test to try to reproduce #101.
=> [MRG] deadlocks at resize time

loky/backend/popen_loky_posix.py, loky/backend/semaphore_tracker.py, loky/backend/spawn.py, loky/backend/synchronize.py
Fix the semaphore tracker bug which duplicates it.
=> FIX semaphore_tracker for all versions

README.md, setup.py
=> [MRG] Add testing guide

.travis.yml, CHANGES.md, loky/__init__.py, loky/backend/context.py, loky/process_executor.py, loky/reusable_executor.py, tests/_executor_mixin.py, tests/test_loky_backend.py, tests/test_loky_module.py
Fixes #111 
This is the initial implementation, I need to add more tests and document better.
I guess the main concern is to make sure this never errors even on some exotic systems. cc @ogrisel
=> [MRG] Fix Detect the number of usable CPU

loky/process_executor.py, loky/reusable_executor.py, setup.py, tests/_executor_mixin.py, tests/conftest.py
Try to fix the deadlock seen in `joblib`: https://travis-ci.org/tomMoral/joblib/jobs/365462067
This is a blocker for joblib/joblib#660
=> FIX shutdown lock

loky/backend/popen_loky_posix.py
Just a tiny internal fix to make the word ordering of this internal parameter name less French.
=> ENH better parameter name for loky process

loky/backend/semaphore_tracker.py, loky/backend/semlock.py, loky/backend/synchronize.py, tests/test_synchronize.py
=> [MRG] Make loky sem_unlink follow the API of _multiprocessing.sem_unlink

CHANGES.md, loky/reusable_executor.py, tests/test_reusable_executor.py
=> Fix bad interaction between max_workers=None and reuse='auto'

CHANGES.md, examples/deadlocks/deadlock_results.py, examples/deadlocks/deadlock_timeout_shutdown.py, examples/reuseable_executor.py, loky/reusable_executor.py, tests/test_reusable_executor.py
=> ENH add initializer argument in get_reusable_executor

LICENSE.txt, MANIFEST.in, setup.cfg
Fix for #136 
@ogrisel  @jakirkham Should we release again or just merge in master?
=> MTN add LICENSE.txt file in loky for packaging

CHANGES.md, loky/backend/utils.py, loky/process_executor.py, tests/test_reusable_executor.py
=> FIX force error at pickling to be pickling errors

CHANGES.md, loky/process_executor.py, tests/test_reusable_executor.py, tests/test_worker_timeout.py
This should make it possible to tackle issues such as: https://github.com/joblib/joblib/issues/721
=> Add protection against memory leaks

.travis.yml, CHANGES.md, continuous_integration/appveyor/runtests.ps1, continuous_integration/travis/runtests.sh, loky/backend/queues.py, loky/process_executor.py, tests/_test_process_executor.py, tests/conftest.py
=> Fix send bytes

CHANGES.md, loky/backend/context.py, loky/backend/popen_loky_posix.py, loky/backend/popen_loky_win32.py, loky/backend/process.py, loky/backend/spawn.py, tests/_test_process_executor.py, tests/test_loky_backend.py, tests/test_process_executor_loky.py
Correctly handle the default context and passing the context in the sub-processes.
=> FIX context logic in loky

loky/backend/context.py
=> FIX cpu_count returns a float

tests/_test_process_executor.py
This makes it possible to have the helper functions inline in the test function body.
=> Do not use __ in attribute name to avoid issues with name mangling

tests/test_worker_timeout.py
Let's see if travis likes it better.
=> MAINT workaround random pypy failure on travis

.travis.yml, CHANGES.md, continuous_integration/travis/runtests.sh, loky/backend/compat.py, loky/process_executor.py, tests/_test_process_executor.py
Print `__causes__` argument in python2.7.
=> ENH improve reporting of causes for python2.7

CHANGES.md, loky/__init__.py, loky/backend/utils.py, loky/process_executor.py, tests/_test_process_executor.py, tests/test_process_executor_forkserver.py, tests/test_reusable_executor.py, tests/utils.py
Display exitcode on `TerminatedWorkerError`.
=> ENH improve reporting TerminatedWorkerError

CHANGES.md, README.md, README.rst, examples/cloudpickle_wrapper.py, loky/backend/reduction.py, loky/cloudpickle_wrapper.py, loky/process_executor.py, setup.py, tests/test_cloudpickle_wrapper.py
Set the default serialization to use `cloudpickle`.
=> ENH default serialization changed to cloudpickle

loky/backend/compat.py, loky/backend/reduction.py
See [here](https://travis-ci.org/joblib/joblib/jobs/449161230)
=> FIX set_causes breaks on python2.7 with Error without msg

loky/backend/reduction.py, loky/process_executor.py, tests/test_cloudpickle_wrapper.py
Send the loky_pickler info with each tasks to have compatible serialization with `set_loky_pickler`
Close #182
=> FIX loky pickler in workers

loky/reusable_executor.py
=> CLN declare _executor_kwargs at a module level

.travis.yml, continuous_integration/appveyor/runtests.ps1, tests/_executor_mixin.py
This should take care of the failing cron jobs. I will merge if CI is green.
=> Fix change in pytest mark API

tests/test_reusable_executor.py
related to [this travis failure](https://travis-ci.org/cloudpipe/cloudpickle/jobs/490049744#L263) in [this cloudpickle PR](https://github.com/cloudpipe/cloudpickle/pull/240)
=> FIX fix nested function test exit signal

.travis.yml, tox.ini
I'm getting some weird failures on #204 in PyPy. Just checking if those failures are unrelated.
=> CI Temporarily allow pypy test suite run to fail

continuous_integration/azure/install.cmd, continuous_integration/azure/test_script.cmd, dev-requirements.txt
Re-enable coverage for the Windows CI.
=> Collect coverage data for Windows CI

continuous_integration/travis/runtests.sh
This should fix the failing CI cron job.
=> Install threadpoolctl for joblib tests

examples/reuse_executor.py, examples/reuseable_executor.py
=> Fix initialization example

CHANGES.md, loky/process_executor.py, tests/_test_process_executor.py
=> increase memory leak detection threshold

README.rst, docs/conf.py
=> DOC remove link to old tommoral repo

CHANGES.md, loky/process_executor.py
=> Concurrent safe iteration over processes

tests/_test_process_executor.py
=> MAINT skip failing test on 32 bit Python

loky/process_executor.py, tests/test_reusable_executor.py
=> FIX skip test on win32+py38+ failing due to #279

.readthedocs.yml, docs/conf.py, docs/index.rst, docs/requirements.txt
=> Fix the sphinx build and readthedocs configs

continuous_integration/install_coverage_subprocess_pth.py, loky/_base.py, loky/backend/__init__.py, loky/backend/_posix_wait.py, loky/backend/context.py, loky/backend/popen_loky_win32.py, loky/backend/queues.py, loky/backend/resource_tracker.py, loky/backend/semlock.py, loky/backend/synchronize.py, loky/process_executor.py, tests/_executor_mixin.py, tests/_test_process_executor.py, tests/test_loky_backend.py, tests/test_loky_module.py, tests/test_resource_tracker.py, tests/test_reusable_executor.py, tests/utils.py
Introducing f-string in place of `%` to reduce the diff in #304
=> MAINT replace % by f-string

docs/conf.py, examples/deadlocks/deadlock_on_failed_pickle.py, examples/deadlocks/deadlock_on_shutdown.py, examples/deadlocks/deadlock_results.py, tests/test_process_executor_forkserver.py, tests/test_process_executor_spawn.py
=> MNT some clean up

loky/__init__.py, loky/cloudpickle_wrapper.py, loky/initializers.py, tests/_executor_mixin.py, tests/conftest.py, tests/test_cloudpickle_wrapper.py, tests/test_futures.py, tests/test_loky_module.py, tests/utils.py
Part of https://github.com/joblib/loky/pull/304.
=> MNT more drop py < 3.7 support

loky/backend/resource_tracker.py, tests/test_resource_tracker.py
=> MNT drop py < 37 support in resource_tracker

loky/backend/popen_loky_posix.py, loky/backend/popen_loky_win32.py
=> MNT drop py < 3.7 support in popen

loky/backend/synchronize.py, tests/test_synchronize.py
=> MNT drop py < 3.7 support in synchronize

loky/backend/_posix_reduction.py, loky/backend/_win_reduction.py, loky/backend/reduction.py
Remove fixes for Python < 3.7 in `reduction.py` to reduce the diff of #304
=> MAINT drop Python < 3.7 in reduction.py

loky/backend/queues.py
=> MNT drop py < 3.7 support in queues

loky/backend/process.py
=> MNT drop py < 3.7 support in process

loky/backend/spawn.py
=> MNT drop py < 3.7 support in spawn

loky/backend/utils.py
=> MNT drop py < 3.7 support in utils

loky/backend/context.py
=> MNT drop py < 3.7 support in context

tests/test_loky_backend.py
=> MNT drop py < 3.7 support in test_loky_backend

tests/utils.py
=> MNT drop py < 3.7 support in test/utils

loky/__init__.py, loky/_base.py, loky/backend/context.py, tests/test_resource_tracker.py
A couple of remaining compatibility changes to be removed.
=> MAINT remove some remaining python < 3.7

tests/test_synchronize.py
=> Make test_semlock_failure independent of previous runs

.azure_pipeline.yml, CHANGES.md, loky/backend/utils.py, loky/process_executor.py, tests/_executor_mixin.py, tests/_test_process_executor.py, tests/test_loky_backend.py, tests/test_loky_module.py, tests/test_reusable_executor.py, tox.ini
=> Fix kill_workers=True and a possible race condition in ExecutorMixin.teardown_method

.azure_pipeline.yml, CHANGES.md, loky/backend/context.py, tests/test_loky_module.py, tox.ini
This should fix oversubscription problems on PyPy / Linux.
=> Leverage psutil to inspect CPU affinity contraints on alternative platforms

setup.py
Noticed while diffing the releases.
=> MAINT fix weird formatting in setup.py

.azure_pipeline.yml, examples/deadlocks/deadlock_on_failed_pickle.py, examples/deadlocks/deadlock_on_shutdown.py, examples/deadlocks/deadlock_results.py, examples/deadlocks/deadlock_timeout_shutdown.py, examples/reuse_executor.py, examples/reuseable_executor.py, loky/__init__.py, loky/process_executor.py, tests/test_resource_tracker.py
current black version is not even available for recent versions of Python.
=> MAINT Bump black version

.azure_pipeline.yml, CHANGES.md, loky/backend/context.py, loky/backend/reduction.py, loky/process_executor.py, tests/_executor_mixin.py, tests/_test_process_executor.py, tests/test_process_executor_forkserver.py, tests/test_process_executor_spawn.py, tox.ini
=> MNT Drop PyPy support

CHANGES.md, loky/process_executor.py, loky/reusable_executor.py, tests/test_reusable_executor.py
=> Fix reusable executor queue size

CHANGES.md, loky/backend/resource_tracker.py
=> FIX check ResourceTracker.__del__ implem

.github/workflows/test.yml, continuous_integration/install.sh, tests/_test_process_executor.py
Start with the CI, check that we can reproduce #466 and then push the fix.
Closes #466.
=> Add new CI for Python 3.14.0rc2 free-threading
